source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'mongo'
gem 'bson_ext'
gem 'phantomjs'
gem 'rspec'
gem 'bson_ext'
gem 'bson'
# gem ''
gem 'mechanize'
gem 'multipart-post'
gem 'deathbycaptcha'
gem 'symmetric-encryption'